-- Releasability tracking: drop the (project, week_monday) primary key so two
-- castings of one project can coexist in the same week.
--
-- Why: adding a placeholder casting (e.g. project #0841 cast 7) into a week
-- that already holds cast 6 of the same project produces two rows with the
-- SAME derived project name and week_monday. The original composite primary
-- key (project, week_monday) — see releasabiltyboarddev/releasability-table-setup.sql —
-- made that second row impossible (23505 on INSERT), which pushed the app into
-- name+week fallback UPDATEs that silently overwrote the sibling casting.
-- The durable identity is now (project_number, casting_number), added by
-- migration/releasability-tracking-add-casting-key.sql; (project, week_monday)
-- is only the addressing scheme for LEGACY rows that predate the casting key.
--
-- This migration:
--   1. adds a surrogate `id BIGINT GENERATED BY DEFAULT AS IDENTITY`;
--   2. drops the old (project, week_monday) primary key (resolved by columns,
--      not by name, so it works whatever the constraint is called);
--   3. promotes `id` to primary key;
--   4. ensures the existing UNIQUE (project_number, casting_number)
--      (releasability_tracking_casting_unique, from the earlier migration)
--      is present without duplicating it;
--   5. re-protects legacy rows with a partial UNIQUE index on
--      (project, week_monday) WHERE casting_number IS NULL, so un-keyed rows
--      still can't duplicate — only keyed sibling castings are exempt.
--
-- Idempotent: every step is guarded (DO blocks / IF NOT EXISTS). Safe to re-run.
-- Safe to run before OR after the matching JS ships: the app no longer issues
-- upsert(onConflict: 'project,week_monday') against this table (it was split
-- into update-then-insert), so nothing depends on the old PK as an arbiter.

-- 1) Surrogate id column (existing rows are backfilled automatically).
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'releasability_tracking'
      AND column_name = 'id'
  ) THEN
    ALTER TABLE releasability_tracking
      ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

-- 2) Drop the composite primary key, but only if the current PK really is
--    (project, week_monday) — never touch the surrogate PK on a re-run.
DO $$
DECLARE
  pk_name TEXT;
  pk_cols TEXT;
BEGIN
  SELECT c.conname,
         (SELECT string_agg(a.attname, ',' ORDER BY x.ord)
            FROM unnest(c.conkey) WITH ORDINALITY AS x(attnum, ord)
            JOIN pg_attribute a
              ON a.attrelid = c.conrelid AND a.attnum = x.attnum)
    INTO pk_name, pk_cols
    FROM pg_constraint c
   WHERE c.conrelid = 'public.releasability_tracking'::regclass
     AND c.contype = 'p';

  IF pk_name IS NOT NULL AND pk_cols = 'project,week_monday' THEN
    EXECUTE format('ALTER TABLE releasability_tracking DROP CONSTRAINT %I', pk_name);
  END IF;
END $$;

-- 3) Promote the surrogate id to primary key (only when the table has no PK,
--    i.e. right after step 2 or when resuming a partially applied run).
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'public.releasability_tracking'::regclass
      AND contype = 'p'
  ) THEN
    ALTER TABLE releasability_tracking
      ADD CONSTRAINT releasability_tracking_pkey PRIMARY KEY (id);
  END IF;
END $$;

-- 4) Ensure the stable casting-key UNIQUE from
--    releasability-tracking-add-casting-key.sql still exists; add it only if
--    missing (that migration created it unguarded, so don't duplicate it).
--    NULLs are distinct, so legacy un-numbered rows never collide here.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'public.releasability_tracking'::regclass
      AND conname = 'releasability_tracking_casting_unique'
  ) THEN
    ALTER TABLE releasability_tracking
      ADD CONSTRAINT releasability_tracking_casting_unique
      UNIQUE (project_number, casting_number);
  END IF;
END $$;

-- 5) Legacy rows (no casting key yet) keep the old one-row-per-project-per-week
--    guarantee via a partial unique index. Keyed rows are exempt — that is the
--    whole point of this migration.
CREATE UNIQUE INDEX IF NOT EXISTS idx_releasability_tracking_legacy_name_week
  ON releasability_tracking (project, week_monday)
  WHERE casting_number IS NULL;
